apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-application-deploy
  labels:
    app: banking-application
spec:
  replias: 3
  selection:
   matchLabels: 
    app: banking-application
  template:
    metadata:
      labels:
        app: banking-application
    spec:
      containers:
       - name: banking-application-container
         image: sruthi2606/banking-application
          ports:
            - containerport: 8082
--
apiVersion: v1
kind: Service
metadata:
  name: banking-application-np-service
  labels:
    app: banking-application
spec:
  selector:
    app: banking-application
    
  type: NodePort
  ports:
   - nodeport: 31032
     port: 8082
     target port: 8082
