apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-application-deploy
  labels:
    app: banking-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-application
  template:
    metadata:
      labels:
        app: banking-application
    spec:
      containers:
      - name: banking-application-container
        image: sruthi2606/banking-application:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-application-np-service
  labels:
    app: banking-application
spec:
  selector:
    app: banking-application

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
